### ISSUE TITLE
Disable escaping safe utf8 characters

### ISSUE THREAD

**Issue by mort3za** [miickel/gulp-angular-templatecache#135]
I just updated to version 2.0.0 and suddenly size of output became doubled because of utf8 characters escaped (All of Persian characters has converted to `\uXYZ`.

Is there a way to completely disable escaping characters ( or better, specify safe range of utf8 characters) ?

**Comment by AdriVanHoudt** [comment]
Same problem here with rendering the € sign

**Comment by bluetech** [comment]
Version 2.0.0 switched to the ["jsesc"](https://github.com/mathiasbynens/jsesc) library, which is described as "generating the shortest possible valid ASCII-only output".  Since templates can contain Unicode characters, I think moving to that library was a mistake, it significantly bloats the output if the templates contain a lot of non-ASCII text.

**Comment by kityan** [comment]
I've made a pull request https://github.com/miickel/gulp-angular-templatecache/pull/142
This will give the posibility to pass `{minimal: true}` from gulp-angular-templatecache to jsesc.

**Comment by miickel** [comment]
merged & published #142, thanks @kityan
